"""
app/models/session.py  (UserSession)
app/models/resume.py
app/models/quiz_result.py
app/models/interview_session.py
app/models/career_score.py
app/models/study_plan.py

All grouped here for Phase 1. Each class maps exactly to the schema
defined in the architecture document.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.database import Base


# ── UserSession ────────────────────────────────────────────────────────────────
class UserSession(Base):
    """
    Tracks active login sessions.
    The id is also used as LangGraph thread_id, giving each user
    a persistent conversation memory across requests.
    """
    __tablename__ = "user_sessions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    refresh_token_hash: Mapped[str | None] = mapped_column(String(255), nullable=True)
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    last_active: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
    # Stores conversation context for LangGraph memory
    context: Mapped[dict | None] = mapped_column(JSONB, nullable=True, default=dict)

    user: Mapped["User"] = relationship("User", back_populates="sessions")  # type: ignore[name-defined]


# ── Resume ─────────────────────────────────────────────────────────────────────
class Resume(Base):
    """
    Stores every resume a user uploads + the Resume Agent's analysis results.
    One user can have multiple resumes (they might upload revised versions).
    """
    __tablename__ = "resumes"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    file_name: Mapped[str] = mapped_column(String(255), nullable=False)
    file_path: Mapped[str] = mapped_column(String(500), nullable=False)

    # Full text extracted from PDF via PyMuPDF
    raw_text: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Resume Agent outputs
    ats_score: Mapped[int | None] = mapped_column(Integer, nullable=True)
    extracted_skills: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    missing_skills: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    suggestions: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    strengths: Mapped[list | None] = mapped_column(JSONB, nullable=True)

    analyzed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    user: Mapped["User"] = relationship("User", back_populates="resumes")  # type: ignore[name-defined]


# ── QuizResult ─────────────────────────────────────────────────────────────────
class QuizResult(Base):
    """
    Every quiz attempt is stored here.
    Accumulates over time to power the Quiz Score component
    of the Career Readiness Engine.
    """
    __tablename__ = "quiz_results"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    session_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("user_sessions.id", ondelete="SET NULL"),
        nullable=True,
    )
    topic: Mapped[str] = mapped_column(String(100), nullable=False)
    difficulty: Mapped[str] = mapped_column(String(20), default="medium")
    quiz_type: Mapped[str | None] = mapped_column(String(20), nullable=True, default="mcq")

    # Full Q&A set as generated by Quiz Agent
    questions: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    # User's submitted answers
    user_answers: Mapped[list | None] = mapped_column(JSONB, nullable=True)

    score: Mapped[int | None] = mapped_column(Integer, nullable=True)   # 0–100
    weak_areas: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    taken_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    user: Mapped["User"] = relationship("User", back_populates="quiz_results")  # type: ignore[name-defined]


# ── InterviewSession ───────────────────────────────────────────────────────────
class InterviewSession(Base):
    """
    Stores each mock interview session.
    session_type distinguishes HR / Technical / Coding interviews,
    which maps to different Interview Agent prompts.
    """
    __tablename__ = "interview_sessions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    # "technical" | "hr" | "coding"
    session_type: Mapped[str] = mapped_column(String(20), nullable=False)
    target_role: Mapped[str | None] = mapped_column(String(100), nullable=True)

    questions: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    readiness_score: Mapped[int | None] = mapped_column(Integer, nullable=True)
    feedback: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    user: Mapped["User"] = relationship("User", back_populates="interview_sessions")  # type: ignore[name-defined]


# ── CareerScore ────────────────────────────────────────────────────────────────
class CareerScore(Base):
    """
    Snapshot of the Career Readiness Score at a point in time.
    Multiple rows per user — the frontend queries the latest one
    and also charts the history for the Progress page.
    """
    __tablename__ = "career_scores"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )

    # Individual component scores (0–100 each)
    resume_score: Mapped[int | None] = mapped_column(Integer, nullable=True)
    skill_score: Mapped[int | None] = mapped_column(Integer, nullable=True)
    interview_score: Mapped[int | None] = mapped_column(Integer, nullable=True)
    quiz_score: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # linkedin_score added in Phase 2
    overall_score: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Top improvement actions from Career Readiness Engine
    recommendations: Mapped[list | None] = mapped_column(JSONB, nullable=True)

    computed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    user: Mapped["User"] = relationship("User", back_populates="career_scores")  # type: ignore[name-defined]


# ── StudyPlan ──────────────────────────────────────────────────────────────────
class StudyPlan(Base):
    """
    Study plans generated by the Study Planner Agent.
    plan_data is a JSONB object structured as:
      { "days": [ { "day": "Monday", "tasks": [...] } ] }
    """
    __tablename__ = "study_plans"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    # "daily" | "weekly" | "monthly"
    plan_type: Mapped[str] = mapped_column(String(20), nullable=False)
    target_role: Mapped[str | None] = mapped_column(String(100), nullable=True)
    plan_data: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    is_active: Mapped[bool] = mapped_column(default=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    user: Mapped["User"] = relationship("User", back_populates="study_plans")  # type: ignore[name-defined]
